# -*- coding: utf-8 -*-
"""Dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPP1unolrjLr2p56HZw-cpd0KrqU2fHA
"""

pip install streamlit plotly pandas

import os
print(os.getcwd())

from google.colab import files

uploaded = files.upload()

import streamlit as st
import pandas as pd
import plotly.express as px

# Load the cleaned dataset
data = pd.read_csv('Lead Site Visit Booking Data.csv')
data['Pushed Date'] = pd.to_datetime(data['Pushed Date'], errors='coerce')
data['Site Visit Date'] = pd.to_datetime(data['Site Visit Date'], errors='coerce')
data['Booking Date'] = pd.to_datetime(data['Booking Date'], errors='coerce')

# Filter data for non-null Booking Values
data = data.dropna(subset=['Booking Value'])

# Trend analysis for number of bookings
data['Month'] = data['Booking Date'].dt.to_period('M')
bookings_per_month = data.groupby('Month').size().reset_index(name='Number of Bookings')
booking_value_per_month = data.groupby('Month')['Booking Value'].sum().reset_index(name='Total Booking Value')

# Convert Period objects to strings for Plotly compatibility
bookings_per_month['Month'] = bookings_per_month['Month'].dt.strftime('%Y-%m')  # Convert Period to string
booking_value_per_month['Month'] = booking_value_per_month['Month'].dt.strftime('%Y-%m')  # Convert Period to string

# Dashboard layout
st.title('Lead Site Visit and Booking Dashboard')

# Number of bookings over time
st.header('Number of Bookings Over Time')
fig1 = px.line(bookings_per_month, x='Month', y='Number of Bookings', title='Number of Bookings Over Time')
st.plotly_chart(fig1)

# Total booking value over time
st.header('Total Booking Value Over Time')
fig2 = px.line(booking_value_per_month, x='Month', y='Total Booking Value', title='Total Booking Value Over Time')
st.plotly_chart(fig2)

# Correlation analysis between site visit and booking value
st.header('Correlation Between Site Visits and Booking Value')
site_visit_data = data.dropna(subset=['Site Visit Date'])
site_visit_data['Days Between Visit and Booking'] = (site_visit_data['Booking Date'] - site_visit_data['Site Visit Date']).dt.days
fig3 = px.scatter(site_visit_data, x='Days Between Visit and Booking', y='Booking Value',
                  color='Booking Project', title='Days Between Site Visit and Booking vs. Booking Value')
st.plotly_chart(fig3)

!streamlit run dashboard.py